Task 1255975: Support “Go to Disassembly” in Call Stack Window for OpenDebugAD7 scenarios
microsoft/MIEngine pull request #1104
Opened 2021-01-30 00:55 UTC by gc46

Before:
![image](https://user-images.githubusercontent.com/60245970/106341614-c3fe5f00-6252-11eb-8937-e42a72fe55dc.png)

After:
![image](https://user-images.githubusercontent.com/60245970/106341618-cbbe0380-6252-11eb-8d1e-8583d63cb831.png)

2021-01-30 01:00 UTC, gc46 commented
To-Do:
- Check status of GetInfo() call
- Add in null checks?
- Use bstrAddress instead of bstrAddressAbsolute? Both have the same value assignment in GetInfo(). (See AD7MemoryAddress.cs, Line 157.)
- Clean up extraneous comments.

2021-01-30 01:07 UTC, WardenGnaw requested changes

2021-01-30 01:07 UTC, WardenGnaw commented on src/OpenDebugAD7/AD7DebugSession.cs
> +                        IDebugCodeContext2 memoryAddress = null;
You will want to move this into the `if (frame != null)` on line 1461

2021-01-30 01:07 UTC, WardenGnaw commented on src/OpenDebugAD7/AD7DebugSession.cs
> +                        memoryAddress.GetInfo(enum_CONTEXT_INFO_FIELDS.CIF_ALLFIELDS, contextInfo); // test -- need to delete; need to check if call is successful
No need to grab all fields, you can just ask for the Address. You will want to validate that the contextInfo also set the flag that it has a value. E.g.
`contextInfo[0].dwFields.HasFlag(enum_CONTEXT_INFO_FIELDS.CIF_ADDRESSABSOLUTE)` before using `contextInfo[0].bstrAddressAbsolute`

2021-01-30 01:08 UTC, gregg-miskelly approved these changes
Otherwise LGTM

2021-01-30 01:08 UTC, gregg-miskelly commented on src/OpenDebugAD7/AD7DebugSession.cs
> +                        memoryAddress.GetInfo(enum_CONTEXT_INFO_FIELDS.CIF_ALLFIELDS, contextInfo); // test -- need to delete; need to check if call is successful
You just want to ask for `enum_CONTEXT_INFO_FIELDS.CIF_ADDRES`

2021-01-30 01:08 UTC, gregg-miskelly commented on src/OpenDebugAD7/AD7DebugSession.cs
> +                        memoryAddress.GetInfo(enum_CONTEXT_INFO_FIELDS.CIF_ALLFIELDS, contextInfo); // test -- need to delete; need to check if call is successful
`memoryAddress?.` since you aren't checking for success

2021-01-30 01:08 UTC, gregg-miskelly commented on src/OpenDebugAD7/AD7DebugSession.cs
> +                        memoryAddress.GetInfo(enum_CONTEXT_INFO_FIELDS.CIF_ALLFIELDS, contextInfo); // test -- need to delete; need to check if call is successful
Should probably have:

```C#
string instructionPointerReference = null;
if (memoryAddress?.GetInfo(enum_CONTEXT_INFO_FIELDS.CIF_ADDRES, contextInfo ==  == HRConstants.S_OK &&
contextInfo[0].dwFields.HasFlag(enum_CONTEXT_INFO_FIELDS.CIF_ADDRESS))
{
    instructionPointerReference = contextInfo[0].bstrAddress;
}

...

{
...
    InstructionPointerReference = instructionPointerReference
```

2021-02-02 19:02 UTC, gregg-miskelly approved these changes

2021-02-02 19:47 UTC, WardenGnaw approved these changes

2021-02-02 19:48 UTC, merged