Bug 1289718: Adding data breakpoint via Breakpoints Window results in..
microsoft/MIEngine pull request #1146
Opened 2021-05-24 20:44 UTC by gc46

.."When '0x0000000000000000' changes (4 bytes)" when input is an expression

Before:
![image](https://user-images.githubusercontent.com/60245970/119405372-ffa3b580-bc95-11eb-9632-083a9a192974.png)

After:
![image](https://user-images.githubusercontent.com/60245970/119404534-cae32e80-bc94-11eb-8835-4e61fd7d1fd5.png)

2021-05-24 20:45 UTC, gc46 commented
Will clean up extraneous comments

2021-05-25 00:15 UTC, gregg-miskelly commented on src/MIDebugEngine/AD7.Impl/AD7PendingBreakpoint.cs
> +                                    if (address.Contains("0x"))
>Contains [](http://example.com/codeflow?start=48&length=8)

You need to be much more strict about these checks.

I think what you want is something like:

```C#
// In AD7Property.cs:
static readonly Lazy<Regex> s_propertyDataBreakpointPattern = new Lazy<Regex>(() => new Regex(@"^(0x[0-9a-fA-F]+),.+"));

internal bool TryParsePropertyDataBreakpoint(string input, out string address)
{
     Match match = s_propertyDataBreakpointPattern.Value.Match(input);
     if (!match.Success)
     {
         address = null;
         return false;
     }
     
     address = match.Captures[0].ToString();
     return true;
}
```

```C#
// Top of the class
static readonly Lazy<Regex> s_addressPattern = new Lazy<Regex>(() => new Regex(@"^0x[0-9a-fA-F]+$"));

// Here
string dataBpExpression = HostMarshal.GetDataBreakpointStringForIntPtr(_bpRequestInfo.bpLocation.unionmember3);

if (AD7Property.TryParsePropertyDataBreakpoint(dataBpExpression, out string addressString))
{
    this.AddressId = dataBpExpression;
    _address = addressString;
}
else 
{
    this.AddressId = null;
    dataBpExpression = dataBpExpression.Trim();    

    if (s_addressPattern.Value.Match(dataBpExpression).Success)
    {
       _address = dataBpExpression;
    }
    else
    {
       _address = Address(dataBpExpression);
    }
}
```

2021-05-25 00:19 UTC, gregg-miskelly commented on src/MIDebugEngine/AD7.Impl/AD7PendingBreakpoint.cs
> +            {
Why are you Task.Run`ing and then waiting?

2021-05-25 00:24 UTC, gregg-miskelly commented on src/MIDebugEngine/AD7.Impl/AD7PendingBreakpoint.cs
> +                                    if (address.Contains("0x"))
Ignore this for the second. I think our approach on this is wrong.

2021-05-25 00:34 UTC, gregg-miskelly requested changes
First, let me make sure I understand the problem you are trying to fix.

Is the problem that if you do this:
1. Start debugging and get into break mode
2. Open the breakpoints window
3. New->Data Breakpoint
4. Type in something which isn't an address

Is that right?
And what you are seeing is that whatever the user typed in during the last step is being given to MIEngine as the return value from HostMarshal.GetDataBreakpointStringForIntPtr?

If so, while it probably would be good to some version of the change I suggested so that we do validate the dataBpExpression that we get from AD7, the bigger problem is that we should be getting an address here.

This is important because the engine doesn't know the current frame. An engine can kind of guess the current frame like you are doing here, but it shouldn't need to. So we should understand why the UI isn't translating the address expression. This could be a UI bug, or this could be a problem with some other part of MIEngine (ex: our memory contexts aren't sufficient).

2021-05-25 15:32 UTC, gc46 commented
@gregg-miskelly, your understanding of the problem is correct. If the user inputs an expression other than an address, the corresponding address displayed is 0x0000000000000000. However, if the user inputs an address, the correct behavior is observed.

To address the return value from HostMarshal.GetDataBreakpointStringForIntPtr(), again, you are correct; if the user inputs "*test", the function returns "*test".

Thus, my current approach is to retrieve the address of the user-input expression if said expression is not an address; I use the return value of HostMarshal.GetDataBreakpointStringForIntPtr() to determine this.

Please let me know if you have any further questions. Thanks!

2021-05-25 16:12 UTC, gc46 commented
In addition to the above, here is what I messaged Charlie on May 20, 2021:
![image](https://user-images.githubusercontent.com/60245970/119531889-38e13180-bd39-11eb-9d75-1dec5b7afe4f.png)

2021-05-25 16:16 UTC, gregg-miskelly commented
@gc46 Thanks! I think this is a bug in the VS UI. I sent you an email yesterday with where I think the bug is.

2021-05-25 16:22 UTC, gc46 commented
@gregg-miskelly - yep, I saw your email. Will look into it. Thank you again!

2021-05-27 21:01 UTC, gc46 commented
@gregg-miskelly, to follow up on your email regarding SetDataLocation() in dbgbp.cpp, I set a breakpoint at the line you highlighted and found the following:

> location
> - DataFullName: null
> - DataExpression: 0x143bb73c L"test"
> - DataCount: 4
> 
> bstrDataExpression: 0x143bb73c L"test"
> 
> GetDebugger()->DoesCurrentStackFrameSupportMetric(metricDataBPAsString): true
> 
> currentLocation
> - DataFullName: null
> - DataExpression: null
> - DataCount: 4
> 
> updatedLocation
> - DataFullName: null
> - DataExpression: 0x13ee0944 L"test"
> - DataCount: 4

Notice that updatedLocation.DataFullName is null; I will investigate this. Furthermore, there is no need to modify the if-condition as DataExpression is already populated and correct. Thanks!

2021-06-08 18:48 UTC, closed without merging